GET http://localhost:8080/snippets
Accept: application/json

###
POST http://localhost:8080/snippets
Content-Type: application/json
Authorization: Basic eric 123

{
  "snippet": {
    "text": "mysnippet"
  }
}
###
POST http://localhost:8080/snippets
Content-Type: application/json
Authorization: Basic unknown wrong

{
  "snippet": {
    "text": "evil snippet"
  }
}
###
